Module8 task1
htmlacademy-ecmascript/1285009-big-trip-12 pull request #13
Opened 2020-08-29 17:51 UTC by NinZZya

2020-08-29 23:31 UTC, AlexMasterov requested changes

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/statistics/statistics.js
<details>
<summary>view/statistics/statistics.js</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/52708fb2c7285ba2dcc1514ba24134d4c2d701b3/src/view/statistics/statistics.js#L96-L121
</details>

```
bar chart: "scales.[x/y]Axes.barThickness" is deprecated. Please use "dataset.barThickness" instead
```

Б2~

2020-08-29 23:31 UTC, AlexMasterov commented on src/main.js
>  newPointButtonElement.addEventListener(`click`, (evt) => {
<details>
<summary>Проблема при нажатии на кнопку</summary>

```
Uncaught TypeError: Cannot read property 'check-in' of undefined
    at createDetailsTemplate (create-details-template.js:9)
    at createPointEditTemplate (point-edit.js:39)
    at PointEdit.getTemplate (point-edit.js:92)
    at PointEdit.getElement (abstract.js:19)
    at PointEdit._setInnerHandlers (point-edit.js:115)
    at new PointEdit (point-edit.js:68)
    at PointNew._renderPointEdit (point-new.js:49)
    at PointNew.init (point-new.js:31)
    at Trip.createPoint (trip.js:109)
    at HTMLButtonElement.<anonymous> (main.js:51)
```
</details>

Д2

> Обсуждалось на лекции

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
>  export default class PointEdit extends AbstractSmartView {
<details>
<summary>Проблема при изменение направления</summary>

```
create-destination-template.js:13 Uncaught TypeError: Cannot read property 'map' of undefined
    at createDestinationTemplate (create-destination-template.js:13)
    at createDetailsTemplate (create-details-template.js:10)
    at createPointEditTemplate (point-edit.js:39)
    at PointEdit.getTemplate (point-edit.js:92)
    at PointEdit.getElement (abstract.js:19)
    at PointEdit.updateElement (abstract-smart.js:36)
    at PointEdit.updateData (abstract-smart.js:28)
    at PointEdit._destinationChangeHandler (point-edit.js:187)
```
</details>

Б2

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
>  export default class PointEdit extends AbstractSmartView {
<details>
<summary>Проблема при сохранении формы с невалидными данными</summary>

```
Uncaught (in promise) Error: Can't update unexisting point
    at Trip.updatePoint (trip.js:88)
    at trip.js:332
```
</details>


Б2

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
>  export default class PointEdit extends AbstractSmartView {
<details>
<summary>Стоимость задана дробью</summary>

![image](https://user-images.githubusercontent.com/700213/91647790-88732500-ea67-11ea-8a35-7fd3f8355079.png)
![image](https://user-images.githubusercontent.com/700213/91647806-b193b580-ea67-11ea-9071-fdf002a0019e.png)


</details>

Нужно использовать целое число.

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
>  export default class PointEdit extends AbstractSmartView {
<details>
<summary>Проблема при выборе/смене типа маршрута</summary>

```
create-destination-template.js:13 Uncaught TypeError: Cannot read property 'map' of undefined
    at createDestinationTemplate (create-destination-template.js:13)
    at createDetailsTemplate (create-details-template.js:10)
    at createPointEditTemplate (point-edit.js:39)
    at PointEdit.getTemplate (point-edit.js:92)
    at PointEdit.getElement (abstract.js:19)
    at PointEdit._getTypeList (point-edit.js:108)
    at PointEdit._typeListClickHandler (point-edit.js:177)
```
</details>

Д2

2020-08-29 23:31 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
>    _offersChangeHandler(evt) {
Презентеру требуется получить список доп. предложений только при обработке нажатия на кнопку `Save`.

2020-08-29 23:31 UTC, AlexMasterov commented on src/model/trip/trip.js
>  export default class Trip extends Observer {
<details>
<summary>Trip</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/52708fb2c7285ba2dcc1514ba24134d4c2d701b3/src/model/trip/trip.js#L83
https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/52708fb2c7285ba2dcc1514ba24134d4c2d701b3/src/model/trip/trip.js#L108
</details>

Д11~

2020-08-29 23:31 UTC, AlexMasterov commented on src/model/trip/trip.js
> +import {diffDate} from "../../utils/date.js";
`diffDate`

Б11~

2020-08-30 05:11 UTC, AlexMasterov requested changes

2020-08-30 05:11 UTC, AlexMasterov commented on src/main.js
> +newPointButtonElement.disabled = true;
Д26

2020-08-30 05:16 UTC, AlexMasterov commented on src/presenter/trip/trip.js
>      if (points.length > 0) {
```diff
- if (points.length > 0) {
+ if (this._tripModel.isEmpty()) {
```

2020-08-30 05:20 UTC, AlexMasterov requested changes

2020-08-30 05:20 UTC, AlexMasterov commented on src/view/point-edit/templates/create-offers-template.js
> +                  ${isOfferIncluded(data.offers, offer) ? `checked` : ``}
<details>
<summary>view/point-edit/templates/create-offers-template.js</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/52708fb2c7285ba2dcc1514ba24134d4c2d701b3/src/view/point-edit/templates/create-offers-template.js#L1-L3
</details>

Б32, Б34

Цикл в цикле. Нужно менять решение.

2020-08-30 16:51 UTC, NinZZya commented on src/model/trip/trip.js
> +      end,
Оставил, т.к. использую при расчете **duration**

  static adaptPointToClient(point) {
    const start = new Date(point.date_from);
    const end = new Date(point.date_to);

    return {
      id: point.id,
      type: point.type,
      destination: point.destination,
      start,
      end,
      **duration: end - start,**
      price: point.base_price,
      offers: point.offers,
      isFavorite: point.is_favorite,
    };
  }

2020-08-30 16:56 UTC, AlexMasterov commented on src/model/trip/trip.js
> +      end,
Извини, забыл и не заметил 😟

2020-08-31 10:05 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
> +  constructor({point = BLANK_POINT, destinations, offers, isAddMode = false}) {
<details>
<summary>Проблема при смене типа маршрута в отсутствие направления</summary>

```
point-edit.js:227 Uncaught TypeError: Cannot read property 'value' of null
    at PointEdit._typeListClickHandler (point-edit.js:227)
```
</details>

Нужно разобраться и доработать 😟

2020-08-31 10:08 UTC, AlexMasterov commented on src/view/point-edit/point-edit.js
> +  constructor({point = BLANK_POINT, destinations, offers, isAddMode = false}) {
<details>
<summary>Проблема с добавлением точки маршрута в избранное в отсутствие направления</summary>

```
api.js:64 PUT https://12.ecmascript.pages.academy/big-trip/points/0 400 (Bad Request)
```
```
trip.js:82 Uncaught (in promise) Error: Can't update unexisting point
    at Trip.updatePoint (trip.js:82)
    at trip.js:335
```
</details>

Нужно разобраться и доработать 😟

2020-08-31 10:12 UTC, AlexMasterov commented on src/view/point-edit/templates/create-offers-template.js
> +export const createOffersTemplate = (renderOffers) => {
`render`Offers

Б3

2020-08-31 19:19 UTC, AlexMasterov commented
Продолжим дорабатывать проект для защиты в след. задание. Осталось совсем немного! 😃

> Столько всего смог исправить!

2020-08-31 19:19 UTC, merged