Module8 task2
htmlacademy-ecmascript/1285009-big-trip-12 pull request #14
Opened 2020-09-01 08:26 UTC by NinZZya

2020-09-02 03:31 UTC, AlexMasterov commented on src/view/point-edit/templates/create-reset-button-template.js
> +const getCaption = (isAddMode, isDeleting) => {
<details>
<summary>getCaption</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/view/point-edit/templates/create-reset-button-template.js#L2-L4

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/view/point-edit/templates/create-reset-button-template.js#L6
</details>

Нужно разделить функцию.

> Плохой дизайн

2020-09-02 03:36 UTC, AlexMasterov commented on src/presenter/trip/trip.js
Если добавить точку маршрута в избранное, то форма редактирования закрывается.

> Также имей в виду, что добавление точки маршрута в избранное не требует нажатия кнопки `Save` и должно происходить сразу: запроса на сервер, получение ответа, сохранение в модель

Нужно исправить (вернуть, как было).

2020-09-02 03:40 UTC, AlexMasterov commented on src/presenter/trip/trip.js
<details>
<summary>utils/type-preposition.js</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/utils/type-preposition.js#L5
</details>

`print`Type

~Б10~

Это не функция, нужно убрать глагол.

> Частое замечание

2020-09-02 03:45 UTC, AlexMasterov commented on src/presenter/point-new/point-new.js
<details>
<summary>presenter/point-new/point-new.js</summary>

https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/presenter/point-new/point-new.js#L13
https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/presenter/point-new/point-new.js#L62
</details>

[`Д 6`](https://up.htmlacademy.ru/ecmascript/12/criteries#d6)
> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

2020-09-02 03:47 UTC, AlexMasterov commented
Обрати внимание на доп. критерии:

[`Д 3`](https://up.htmlacademy.ru/ecmascript/12/criteries#d3)
> Название методов и свойств объектов не содержит название объектов

[`Д 6`](https://up.htmlacademy.ru/ecmascript/12/criteries#d6)
> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

[`Д 8`](https://up.htmlacademy.ru/ecmascript/12/criteries#d8)
> Методы внутри классов упорядочены

2020-09-02 03:51 UTC, AlexMasterov requested changes

2020-09-02 03:51 UTC, AlexMasterov commented on src/presenter/point/point.js
> +  successHandler() {
https://github.com/htmlacademy-ecmascript/1285009-big-trip-12/blob/5706881b922560ede7825a0a83a3d38901a1e8de/src/presenter/trip/trip.js#L350

Б10

В этом месте обработчик `successHandler` вызывается напрямую.

Нужно исправить название метода.

2020-09-02 03:59 UTC, AlexMasterov requested changes

2020-09-02 03:59 UTC, AlexMasterov commented on src/presenter/point-new/point-new.js
Сейчас статистика не реагирует на изменение фильтров.

Скрой фильтры или доработай.

2020-09-03 03:27 UTC, AlexMasterov approved these changes
👍

2020-09-03 03:27 UTC, AlexMasterov commented on src/view/tabs/tabs.js
>    _tabsClickHandler(evt) {
`Tabs`._`tabs`ClickHandler

Д3~

```diff
- _tabsClickHandler(evt) {
+ _сlickHandler(evt) {
```

2020-09-03 03:28 UTC, merged

2020-09-03 07:02 UTC, NinZZya commented on src/view/tabs/tabs.js
>    _tabsClickHandler(evt) {
Тут я намеренно оставил т.к. думал о Д4. Из названия обработчика события и функции-коллбэка следует, что это за обработчик. Т.е. на tabs событие Click которое является обработчиком. Событие может быть на каждом tab. Логика у меня такая.

При этом метод по Д3 - setClickHandler